sudo: required
services:
    - docker
before_install:
    - docker build -t react-test-aws-eb -f ./client/Dockerfile.dev ./client
script:
    - docker run react-test-aws-eb npm test -- --coverage
after_success:
    - docker build -t complex-client ./client
    - docker build -t complex-nginx ./nginx
    - docker build -t complex-server ./server
    - docker build -t complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push new built images to docker hub
    - docker push complex-client
    - docker push complex-nginx
    - docker push complex-server
    - docker push complex-worker

