sudo: required
services:
    - docker
before_install:
    - docker build -t react-test-aws-eb -f ./client/Dockerfile.dev ./client
script:
    - docker run react-test-aws-eb npm test -- --coverage
after_success:
    - docker build -t sazzadk/complex-client ./client
    - docker build -t sazzadk/complex-nginx ./nginx
    - docker build -t sazzadk/complex-server ./server
    - docker build -t sazzadk/complex-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push new built images to docker hub
    - docker push sazzadk/complex-client
    - docker push sazzadk/complex-nginx
    - docker push sazzadk/complex-server
    - docker push sazzadk/complex-worker

